### ISSUE TITLE
Cache_tags - error using rails with solr, foreman, unicorn and tag-it jquery-plugin

### ISSUE THREAD

**Issue by sauron** [bradphelan/rocket_tag#11]
First of all, I've already checked the issues related with this one that I am reporting.

I've created a demo app so you can clone and try to reproduce the bug.
https://github.com/sauron/test-rocket-tag-solr-foreman

The weird thing is that I am using rails 3.2.3 with solr foreman unicorn and the tag-it plugin.
Apparently if the tag attribute is not present in the form, it raises the exception, but, after a few test, realize that everytime that the model change, it fails with the exception
_undefined local variable or method `cache_tags' for #<Product:..._
Hope it helps, it took me a while try to resolve this, but I coudn't.

So, I hope you can help me whit this.
Thanks.

**Comment by rilian** [comment]
i have exactly same issue for a generic model with rocket_tag (no solr or foreman)

have tried adding a cache_tag def to the model but then it gives an exception on unexistent 'reload_context'

anyway, looks like cache_tag does not fail on 0.2.0, please check out differences

**Comment by sauron** [comment]
Thanks for your tip rilian,

This workaround works. But of course will be great to fully enjoy all the potential of rocket-tag.

Best.

**Comment by kayluhb** [comment]
I'm also experiencing this issue with a generic model and rails 3.2.4 running with thin.

**Comment by Beans0063** [comment]
I had the same issue using 0.3.1 from rubygems, but it seems the fix is in master on github.  Try pointing your bundle to  use github as the source.

**Comment by sauron** [comment]
Hey Beans0063,
Thanks, but actually I downgraded the version to 0.2.0, just in case.
I'm waiting for the new stable version.

Best.

**Comment by bradphelan** [comment]
I've pushed a new version recently. Closing the bug. Please reopen if there is still a problem

**Comment by sauron** [comment]
Great work!
Works as expected.

Thanks for your collaboration.

**Comment by bradphelan** [comment]
Glad you like the tool. Are you using it in a production environment. Just curious?

**Comment by sauron** [comment]
Kinda :D
Right now it is on a "Private Beta"
As soon as it gets live, let you know.

Best.

**Comment by bradphelan** [comment]
Anyway nice to know it's out in the wild somewhere being useful ;)

**Comment by rilian** [comment]
I'm using it on production on a small site :) Thanks for updates - I'll test new version in evening

**Comment by rilian** [comment]
0 failures on rocket_tag 0.5.0
