### ISSUE TITLE
0.2.0 NoMethodError (undefined method `map' for nil:NilClass):

### ISSUE THREAD

**Issue by rilian** [bradphelan/rocket_tag#14]
when passing nil to model tags=

this may happen if tags field is empty in the form

**Comment by derekcroft** [comment]
This is fixed on master as of pull request 12: https://github.com/bradphelan/rocket_tag/pull/12.  @bradphelan are you planning another release soon?

**Comment by bradphelan** [comment]
I think this is pushed out in a recent release. Closing.
