### ISSUE TITLE
destroy_tags_for_context generates invalid SQL statement

### ISSUE THREAD

**Issue by Beans0063** [bradphelan/rocket_tag#16]
My model uses attr_taggable :genres

When saving I get a SQL error accessing column `taggings`.`genres`

 SQL (0.7ms)  DELETE FROM `taggings` WHERE `taggings`.`taggable_id` = 1 AND `taggings`.`taggable_type` = 'Operator' AND `taggings`.`context` = `taggings`.`genres`
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'taggings.genres' in 'where clause': DELETE FROM `taggings` WHERE `taggings`.`taggable_id` = 1 AND `taggings`.`taggable_type` = 'Operator' AND `taggings`.`context` = `taggings`.`genres`

I'm not too familiar with squeel, but using ActiveRecord in taggings_for_context solves the issue for me:

https://github.com/Beans0063/rocket_tag/commit/f0eb7aa4ebec9aafb2ffa4280e341e3031b3643a

**Comment by al** [comment]
+1

**Comment by rilian** [comment]
i have investigated and found it started failing on squeel 1.0.5

works fine on squeel 1.0.1

**Comment by Beans0063** [comment]
I encountered a similar issue with tagged_similar

This solved it for me: https://github.com/Beans0063/rocket_tag/commit/345177154f0fd52f055c0a0792f77c50391e3a95

**Comment by keithpitt** [comment]
I've opened a pull request on this one: https://github.com/bradphelan/rocket_tag/pull/19

The tests were all failing before my commits.

**Comment by bradphelan** [comment]
Closing as a pull request fixes this
