### ISSUE TITLE
postgresql group by issues

### ISSUE THREAD

**Issue by zentrification** [bradphelan/rocket_tag#21]
v0.5.1 introduces a regression in postgresql (v9.1.3 here), the group by clause does not contain the taggings.id or tags.id columns

also applies to ModelName.tagged_with

1.9.3p0 :001 > ModelName.tags
RocketTag::Tag Load (0.7ms)
    SELECT "tags".*
    FROM (SELECT count("tags"."id") AS tags_count, *
            FROM "tags"
            INNER JOIN "taggings" ON "taggings"."tag_id" = "tags"."id"
                WHERE "taggings"."taggable_type" = 'ModelName'
                AND "taggings"."taggable_id"
                IN (SELECT "model_name"."id" FROM "model_name" )
            GROUP BY "tags"."id", "tags"."name"
            ORDER BY tags_count desc)
    tags
PG::Error: ERROR:  column "taggings.id" must appear in the GROUP BY clause or be used in an aggregate function

**Comment by bradphelan** [comment]
fixed by sha: b986d490527165b74
