### ISSUE TITLE
using rocket_tag for implementing facebook-like mention system 

### ISSUE THREAD

**Issue by remon** [bradphelan/rocket_tag#23]
I think these gem could be used for implementing these system ,,but actually I have no idea for doing these right now ?...if you have any ideas for that can you tell me ..I think it will be great moving up for the rocket_tag gem

**Comment by bradphelan** [comment]
Not really sure what you are asking.

**Comment by remon** [comment]
I mean ,,how we can use these gem in rails simple social network application ,,where user have posts ,,,and in each post he could mention a friend ,,,

**Comment by bradphelan** [comment]
You are in the wrong place. This is just a basic tagging engine. Nothing to do with social networking. If you want a social networking engine in rails have a look at

http://communityengine.org/

**Comment by bradphelan** [comment]
I have had a look at all the issues you have raised on many projects on github recently. I think you have the wrong idea of what the issues are for. They are not a general question and answer place. You may get more help here

http://stackoverflow.com

where people will show you how to solve some problems.

github issues are for feature requests and bugs normally.
