### ISSUE TITLE
Rocket_tag won't install in Rails 4.0.0.beta

### ISSUE THREAD

**Issue by kipcole9** [bradphelan/rocket_tag#28]
Dependencies prevent installation in a Rails 4 (beta) application with the following bundler errors:

Fetching gem metadata from https://rubygems.org/......
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    rocket_tag (>= 0) ruby depends on
      activerecord (~> 3.1.0.alpha) ruby

```
rails (>= 0) ruby depends on
  activerecord (4.0.0.beta)
```

**Comment by amnesia7** [comment]
Hi @kipcole9, I was wondering whether you have a version of `rocket_tag` that's compatible with rails 4?

I'm trying to update my app to rails 4 and was wondering whether there is a version/fork of `rocket_tag` compatible with rails 4 or whether it would be easier to convert to using `acts_as_taggable_on` instead.

Thanks

**Comment by kipcole9** [comment]
Sorry, I don't have a rails 4 compatible branch, I ended up rolling my own for a current project.

**Comment by amnesia7** [comment]
Thanks anyway. Since rocket_tag is so similar to acts-as-taggable-on I've decided to use that gem instead which is already rails 4 compatible.
