### ISSUE TITLE
undefined local variable or method `cache_tags' after "instance methods unless required" commit

### ISSUE THREAD

**Issue by antonovga** [bradphelan/rocket_tag#3]
Hi, there is some strange behaviour after removing instance method.

Rails 3.2.1 ruby 1.9.3, rocket_tag 0.3.1

Before 0.3.0:
Run rails server, change some stuff in view/controller/model which addresses to any model with rocket_tag, press f5, everything is ok, continue developing.

After 0.3.0 (after commit removing inclusion instance methods by default):
Run rails server,change some stuff in view/controller/model which addresses to any model with rocket_tag, press f5, getting an error undefined local variable or method `cache_tags' for "_object_with_rocket_tags". I have to restart rails server, then everything is fine. This behaviour ruins developing process, cause restarting server every time you touch a model with tags is   sad.

Tested with different commits from repo, the problem exactly begins from commit with removing instance methods.
Having not enough experience in ruby, but as I understand the problem is in reinitialising model in developer mode.

I don't say it is a bug, but it is really really unconvenient.

update:
problem is in this variable @@acts_as_rocket_tag in taggable.rb around line 230(i don't know hot to post a link to the code in github) it sets to false only with initial loading(as i understand)

**Comment by asymmetric** [comment]
+1. I also had this issue while running `rocket_tag` in production - strangely enough it doesn't happen when developing locally.
