### ISSUE TITLE
tagger?

### ISSUE THREAD

**Issue by mauriciopasquier** [bradphelan/rocket_tag#30]
I couldn't find any use of `tagger` in the source code, readme or specs..
What's the best way to set it and use it while creating a tag or in the models so it is handled automatically?

Thanks

**Comment by bradphelan** [comment]
I don't understand your question? What is it you want to do. The
documentation and specs are quite extensive on how to use rocket tag.

**Comment by mauriciopasquier** [comment]
I don't see where or how is `tagger_id` and `tagger_type` determined in the `taggings` table. If I add tags to a model (e.g. `@model.tags = ["foo", "bar"]`), those fields remain empty. What would be the best way to set or determine who is tagging the model?

I'm thinking something along the lines of `@model.tags = ["foo", "bar"], :tagger => current_user`, but I don't see it anywhere.

Sorry if it is something really obvious and I missed it, and thanks for your time.

**Comment by bradphelan** [comment]
I think I didn't implement that feature in the end. Sorry.

**Comment by mauriciopasquier** [comment]
No problem! I might end up implementing it if I need it. I'll send you a pull request in that case.

o/
