### ISSUE TITLE
Match exact tags

### ISSUE THREAD

**Issue by manuelmeurer** [bradphelan/rocket_tag#41]
I just found this library after getting annoyed at the amount of bugs and lack of support in acts-as-taggable-on. It looks really great and I'd love to just jump in and switch.

One thing I desperately need is to match tags _exactly_ and I'm not sure it's possible with rocket_tag.
To clarify:

``` ruby
class TaggableModel < ActiveRecord::Base
  attr_taggable :skills
end 

item1 = TaggableModel.create(skills: ["kiting", "surfing"])
item2 = TaggableModel.create(skills: ["kiting", "surfing", "coding"])

# Now I need to be able to find items that have exactly these skills: ["kiting", "surfing"]
# Which would be only item1

# This doesn't work:
TaggableModel.tagged_with ["kiting", "surfing"]
#=> [item1, item2]

# Neither does this:
TaggableModel.tagged_with ["kiting", "surfing"], all: true
#=> [item1, item2]

# I need something like this:
TaggableModel.tagged_with ["kiting", "surfing"], exact: true
#=> [item1]
```

Does anyone else need this functionality or is it just me?

How hard would it be to add this?
I'm happy to submit a pull request but I had a look at `RocketTag::Taggable::ClassMethods.tagged_with` and couldn't immediately see how to implement it.

Any pointers would be welcome! :smile:

**Comment by fntz** [comment]
You can use something like this

```
  q = ["kiting", "surfing"]
  TaggableModel.tagged_with(q).select{|z| z.skills == q}
  #=> [item1]
```

**Comment by manuelmeurer** [comment]
Yes, that is how I'm doing it right now but there are two problems:
1. `TaggableModel.tagged_with(["kiting", "surfing"])` could potentially be a lot of records, which would all have to be loaded into memory to find the one(s) I really want.
2. `select` breaks the chainability with additional `ActiveRecord::Relation` methods.

Would it be very hard to implement something like `exact: true`?
As I said, I'd be happy to give it a shot, just wanted to check first if it was trivial or not.

**Comment by bradphelan** [comment]
What you want is the :all => true option as detailed on the readme.

**Comment by manuelmeurer** [comment]
But in my tests the `all` option also finds records that have _more_ tags than the ones specified, e.g. I search for `["kiting", "surfing"]` and find records that have `["kiting", "surfing", "coding"]`. Is that not how it's supposed to work?

**Comment by bradphelan** [comment]
Then you will want to add a condition on : tags_count to ensure you return
records with a tags count equal to the number of tags you are looking for.

**Comment by bradphelan** [comment]
See the readme again for details

**Comment by manuelmeurer** [comment]
Unfortunately that doesn't work either. `tags_count` seems to be the number of _matched tags_, not the total number of tags on the returned records. So `TaggableModel.tagged_with(["kiting", "surfing"]).where{tags_count==2}` would still return records with `["kiting", "surfing", "coding"]`. But again, maybe this is not the intended behavior?

**Comment by bradphelan** [comment]
You are right that is probably the behaviour. Looks like you might have to
dive into the code :)

**Comment by manuelmeurer** [comment]
Ok cool. That means you would accept a pull request that adds the `exact` parameter? :smile:

**Comment by manuelmeurer** [comment]
It was easier than I expected. As it says in the pull request, I will add specs and some examples in the README soon, just wanted to get the functionality out there already so I can start using it. Please comment and improve if possible!
