### ISSUE TITLE
syntax error after installing rocket_tag gem

### ISSUE THREAD

**Issue by rcanand** [bradphelan/rocket_tag#5]
Platform: ruby 1.8.7 on mac osx lion, rails 3.2.1, rocket_tag installed as a gem
When I try to run rails server (or rails generate rocket_tag:migration), I get a syntax error as follows:

/Library/Ruby/Gems/1.8/gems/rocket_tag-0.3.1/lib/rocket_tag/taggable.rb:157: syntax error, unexpected '.', expecting kEND (SyntaxError)
            .select("#{self.table_name}.*").
             ^

**Comment by bradphelan** [comment]
Ruby 1.9.2 + only sorry
